name: nfc_demo
description: A Flutter project to manage NFC tag.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  nfc_manager: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.5

flutter:
  uses-material-design: true
